name: DevSecOps Security Scan

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  id-token: write  # Required for OIDC, e.g., Azure login

jobs:
  devsecops:
    name: Run DevSecOps Tools
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # --- Snyk ---
    - name: Set up Snyk CLI
      uses: snyk/actions/setup@v2

    - name: Run Snyk Test
      run: snyk test --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Monitor with Snyk (optional)
      run: snyk monitor --all-projects
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    # --- Trivy ---
    - name: Run Trivy FS scan (IaC + Secrets + SCA)
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: fs
        scan-ref: .
        scanners: vuln,config,secrets
        format: table

    # --- OWASP ZAP (DAST) ---
    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.11.0
      with:
        target: 'https://your-staging-app-url.com'  # replace with test/staging URL
        fail_action: false  # optional: set to true to fail on issues
