name: DevSecOps Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write
  id-token: write  # Needed for Azure OIDC login

jobs:
  security-checks:
    name: Run DevSecOps Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      ###  SAST: CodeQL
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java, javascript, python

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

      ###  SCA: Snyk
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions@v2
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor

      ###  IaC Security: Checkov
      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform  # change if needed

      ###  Container Scan: Trivy
      - name: Build Docker Image
        run: docker build -t myapp:latest .

      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: myapp:latest
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      ###  Azure Key Vault Example (Optional)
      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Fetch Secret from Azure Key Vault
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: <your-keyvault-name>
          secrets: |
            MY_SECRET

      ###  DAST (Optional): OWASP ZAP Scan after deploy
      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.11.0
        with:
          target: 'https://your-staging-app-url.com'

